<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MagmaEdit.Broker</RootNamespace>
    <AssemblyName>MagmaEdit.Broker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MagmaEdit.Integration\MagmaEdit.Integration.csproj" />
  </ItemGroup>
</Project>
