<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MagmaEdit.Core</RootNamespace>
    <AssemblyName>MagmaEdit.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\third_party\sprocket\src\Sprocket.Core\Sprocket.Core.csproj" />
    <ProjectReference Include="..\..\third_party\sprocket\src\Sprocket.Media\Sprocket.Media.csproj" />
  </ItemGroup>
</Project>
