<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MagmaEdit.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/MagmaEdit.Core/MagmaEdit.Core.csproj" />
    <ProjectReference Include="../../src/MagmaEdit.Media.Sprocket/MagmaEdit.Media.Sprocket.csproj" />
    <ProjectReference Include="../../src/MagmaEdit.Integration/MagmaEdit.Integration.csproj" />
    <ProjectReference Include="../../src/MagmaEdit.Plugin.Abstractions/MagmaEdit.Plugin.Abstractions.csproj" />
    <ProjectReference Include="../../src/MagmaEdit.PluginHost/MagmaEdit.PluginHost.csproj" />
    <ProjectReference Include="../MagmaEdit.PluginHost.TestPlugin/MagmaEdit.PluginHost.TestPlugin.csproj" />
  </ItemGroup>
</Project>
